apiVersion: v1
kind: Service
metadata:
  name: tradingservice
  namespace: assetcompass
  labels:
    app: tradingservice
spec:
  selector:
    app: tradingservice
  ports:
    - name: http
      port: 80
      targetPort: 8083
