package com.assetcompass.gateway.domain;

import static com.assetcompass.gateway.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class IncomeEventAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIncomeEventAllPropertiesEquals(IncomeEvent expected, IncomeEvent actual) {
        assertIncomeEventAutoGeneratedPropertiesEquals(expected, actual);
        assertIncomeEventAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIncomeEventAllUpdatablePropertiesEquals(IncomeEvent expected, IncomeEvent actual) {
        assertIncomeEventUpdatableFieldsEquals(expected, actual);
        assertIncomeEventUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIncomeEventAutoGeneratedPropertiesEquals(IncomeEvent expected, IncomeEvent actual) {
        assertThat(actual)
            .as("Verify IncomeEvent auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIncomeEventUpdatableFieldsEquals(IncomeEvent expected, IncomeEvent actual) {
        assertThat(actual)
            .as("Verify IncomeEvent relevant properties")
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getEventDate()).as("check eventDate").isEqualTo(expected.getEventDate()))
            .satisfies(a ->
                assertThat(a.getAmount()).as("check amount").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getAmount())
            )
            .satisfies(a -> assertThat(a.getCurrency()).as("check currency").isEqualTo(expected.getCurrency()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIncomeEventUpdatableRelationshipsEquals(IncomeEvent expected, IncomeEvent actual) {
        assertThat(actual)
            .as("Verify IncomeEvent relationships")
            .satisfies(a -> assertThat(a.getAccount()).as("check account").isEqualTo(expected.getAccount()))
            .satisfies(a -> assertThat(a.getAsset()).as("check asset").isEqualTo(expected.getAsset()));
    }
}
