package com.assetcompass.gateway.domain;

import static com.assetcompass.gateway.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class PositionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPositionAllPropertiesEquals(Position expected, Position actual) {
        assertPositionAutoGeneratedPropertiesEquals(expected, actual);
        assertPositionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPositionAllUpdatablePropertiesEquals(Position expected, Position actual) {
        assertPositionUpdatableFieldsEquals(expected, actual);
        assertPositionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPositionAutoGeneratedPropertiesEquals(Position expected, Position actual) {
        assertThat(actual)
            .as("Verify Position auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPositionUpdatableFieldsEquals(Position expected, Position actual) {
        assertThat(actual)
            .as("Verify Position relevant properties")
            .satisfies(a ->
                assertThat(a.getQuantity()).as("check quantity").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getQuantity())
            )
            .satisfies(a ->
                assertThat(a.getAverageCost())
                    .as("check averageCost")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getAverageCost())
            )
            .satisfies(a ->
                assertThat(a.getCurrentValue())
                    .as("check currentValue")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getCurrentValue())
            )
            .satisfies(a -> assertThat(a.getCurrency()).as("check currency").isEqualTo(expected.getCurrency()))
            .satisfies(a -> assertThat(a.getLastSyncedAt()).as("check lastSyncedAt").isEqualTo(expected.getLastSyncedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPositionUpdatableRelationshipsEquals(Position expected, Position actual) {
        assertThat(actual)
            .as("Verify Position relationships")
            .satisfies(a -> assertThat(a.getAccount()).as("check account").isEqualTo(expected.getAccount()))
            .satisfies(a -> assertThat(a.getAsset()).as("check asset").isEqualTo(expected.getAsset()));
    }
}
