package com.assetcompass.gateway.domain;

import static com.assetcompass.gateway.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class RebateAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRebateAllPropertiesEquals(Rebate expected, Rebate actual) {
        assertRebateAutoGeneratedPropertiesEquals(expected, actual);
        assertRebateAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRebateAllUpdatablePropertiesEquals(Rebate expected, Rebate actual) {
        assertRebateUpdatableFieldsEquals(expected, actual);
        assertRebateUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRebateAutoGeneratedPropertiesEquals(Rebate expected, Rebate actual) {
        assertThat(actual)
            .as("Verify Rebate auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRebateUpdatableFieldsEquals(Rebate expected, Rebate actual) {
        assertThat(actual)
            .as("Verify Rebate relevant properties")
            .satisfies(a -> assertThat(a.getRebateDate()).as("check rebateDate").isEqualTo(expected.getRebateDate()))
            .satisfies(a ->
                assertThat(a.getAmount()).as("check amount").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getAmount())
            )
            .satisfies(a -> assertThat(a.getCurrency()).as("check currency").isEqualTo(expected.getCurrency()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRebateUpdatableRelationshipsEquals(Rebate expected, Rebate actual) {
        assertThat(actual)
            .as("Verify Rebate relationships")
            .satisfies(a -> assertThat(a.getAccount()).as("check account").isEqualTo(expected.getAccount()))
            .satisfies(a -> assertThat(a.getOperation()).as("check operation").isEqualTo(expected.getOperation()));
    }
}
