package com.assetcompass.gateway.domain;

import static com.assetcompass.gateway.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class TaxEventAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTaxEventAllPropertiesEquals(TaxEvent expected, TaxEvent actual) {
        assertTaxEventAutoGeneratedPropertiesEquals(expected, actual);
        assertTaxEventAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTaxEventAllUpdatablePropertiesEquals(TaxEvent expected, TaxEvent actual) {
        assertTaxEventUpdatableFieldsEquals(expected, actual);
        assertTaxEventUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTaxEventAutoGeneratedPropertiesEquals(TaxEvent expected, TaxEvent actual) {
        assertThat(actual)
            .as("Verify TaxEvent auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTaxEventUpdatableFieldsEquals(TaxEvent expected, TaxEvent actual) {
        assertThat(actual)
            .as("Verify TaxEvent relevant properties")
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getTaxDate()).as("check taxDate").isEqualTo(expected.getTaxDate()))
            .satisfies(a ->
                assertThat(a.getAmount()).as("check amount").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getAmount())
            )
            .satisfies(a -> assertThat(a.getCurrency()).as("check currency").isEqualTo(expected.getCurrency()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTaxEventUpdatableRelationshipsEquals(TaxEvent expected, TaxEvent actual) {
        assertThat(actual)
            .as("Verify TaxEvent relationships")
            .satisfies(a -> assertThat(a.getAccount()).as("check account").isEqualTo(expected.getAccount()))
            .satisfies(a -> assertThat(a.getOperation()).as("check operation").isEqualTo(expected.getOperation()))
            .satisfies(a -> assertThat(a.getIncomeEvent()).as("check incomeEvent").isEqualTo(expected.getIncomeEvent()));
    }
}
