apiVersion: v1
kind: Service
metadata:
  name: portfolioservice
  namespace: assetcompass
  labels:
    app: portfolioservice
spec:
  selector:
    app: portfolioservice
  ports:
    - name: http
      port: 80
      targetPort: 8081
