package com.assetcompass.portfolio.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AssetRatioAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssetRatioAllPropertiesEquals(AssetRatio expected, AssetRatio actual) {
        assertAssetRatioAutoGeneratedPropertiesEquals(expected, actual);
        assertAssetRatioAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssetRatioAllUpdatablePropertiesEquals(AssetRatio expected, AssetRatio actual) {
        assertAssetRatioUpdatableFieldsEquals(expected, actual);
        assertAssetRatioUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssetRatioAutoGeneratedPropertiesEquals(AssetRatio expected, AssetRatio actual) {
        assertThat(actual)
            .as("Verify AssetRatio auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssetRatioUpdatableFieldsEquals(AssetRatio expected, AssetRatio actual) {
        assertThat(actual)
            .as("Verify AssetRatio relevant properties")
            .satisfies(a -> assertThat(a.getRatio()).as("check ratio").isEqualTo(expected.getRatio()))
            .satisfies(a -> assertThat(a.getEffectiveFrom()).as("check effectiveFrom").isEqualTo(expected.getEffectiveFrom()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssetRatioUpdatableRelationshipsEquals(AssetRatio expected, AssetRatio actual) {
        assertThat(actual)
            .as("Verify AssetRatio relationships")
            .satisfies(a -> assertThat(a.getAsset()).as("check asset").isEqualTo(expected.getAsset()));
    }
}
