package com.assetcompass.portfolio.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BrokerAccountAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBrokerAccountAllPropertiesEquals(BrokerAccount expected, BrokerAccount actual) {
        assertBrokerAccountAutoGeneratedPropertiesEquals(expected, actual);
        assertBrokerAccountAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBrokerAccountAllUpdatablePropertiesEquals(BrokerAccount expected, BrokerAccount actual) {
        assertBrokerAccountUpdatableFieldsEquals(expected, actual);
        assertBrokerAccountUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBrokerAccountAutoGeneratedPropertiesEquals(BrokerAccount expected, BrokerAccount actual) {
        assertThat(actual)
            .as("Verify BrokerAccount auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBrokerAccountUpdatableFieldsEquals(BrokerAccount expected, BrokerAccount actual) {
        assertThat(actual)
            .as("Verify BrokerAccount relevant properties")
            .satisfies(a -> assertThat(a.getExternalAccountId()).as("check externalAccountId").isEqualTo(expected.getExternalAccountId()))
            .satisfies(a -> assertThat(a.getDisplayName()).as("check displayName").isEqualTo(expected.getDisplayName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBrokerAccountUpdatableRelationshipsEquals(BrokerAccount expected, BrokerAccount actual) {
        assertThat(actual)
            .as("Verify BrokerAccount relationships")
            .satisfies(a -> assertThat(a.getBroker()).as("check broker").isEqualTo(expected.getBroker()));
    }
}
