package com.assetcompass.portfolio.domain;

import static com.assetcompass.portfolio.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class ValuationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertValuationAllPropertiesEquals(Valuation expected, Valuation actual) {
        assertValuationAutoGeneratedPropertiesEquals(expected, actual);
        assertValuationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertValuationAllUpdatablePropertiesEquals(Valuation expected, Valuation actual) {
        assertValuationUpdatableFieldsEquals(expected, actual);
        assertValuationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertValuationAutoGeneratedPropertiesEquals(Valuation expected, Valuation actual) {
        assertThat(actual)
            .as("Verify Valuation auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertValuationUpdatableFieldsEquals(Valuation expected, Valuation actual) {
        assertThat(actual)
            .as("Verify Valuation relevant properties")
            .satisfies(a -> assertThat(a.getSnapshotDate()).as("check snapshotDate").isEqualTo(expected.getSnapshotDate()))
            .satisfies(a ->
                assertThat(a.getTotalValue())
                    .as("check totalValue")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getTotalValue())
            )
            .satisfies(a -> assertThat(a.getCurrency()).as("check currency").isEqualTo(expected.getCurrency()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertValuationUpdatableRelationshipsEquals(Valuation expected, Valuation actual) {
        assertThat(actual)
            .as("Verify Valuation relationships")
            .satisfies(a -> assertThat(a.getAccount()).as("check account").isEqualTo(expected.getAccount()));
    }
}
